<html>
<head>
    <?php include_once 'api/views/__head.tpl'; ?>
</head>
<body>
<?php include_once 'api/views/__native.tpl'?>
<main class="Main">
    <div class="Container">
        <div class="TermsPage u-margin-bottom-xl u-margin-top-lg">
            <h2>EncryptBuy Terms of Use</h2>
            <p>Last Updated: April 16, 2018</p>
            <!--
            <p>CryptoKitties is a distributed application that runs on the Ethereum network, using specially-developed smart contracts (each, a “Smart Contract”) to enable users to own, transfer, and breed genetically unique digital cats, which can then be visualized on a website that the user can interact with (the “Site”). The Smart Contracts and the Site are collectively referred to in these Terms as the “App”. Using the App, users can view their cats and use the Smart Contracts to acquire, trade, and breed cats with other App users via clock auction.</p>
            <p>Launch Labs, Inc. d/b/a Axiom Zen (&quot;Axiom Zen&quot;, &quot;we&quot;, or &quot;us&quot;) is making the App available to you. Before you use the App, the Smart Contracts, or the Site, however, you will need to agree to these Terms of Use and any terms and conditions incorporated herein by reference (collectively, these “Terms&quot;). PLEASE READ THESE TERMS CAREFULLY BEFORE USING THE APP, THE SMART CONTRACTS, OR THE SITE. THESE TERMS GOVERN YOUR USE OF THE APP, THE SMART CONTRACTS, AND THE SITE, UNLESS WE HAVE EXECUTED A SEPARATE WRITTEN AGREEMENT WITH YOU FOR THAT PURPOSE. WE ARE ONLY WILLING TO MAKE THE APP, THE SMART CONTRACTS, AND THE SITE AVAILABLE TO YOU IF YOU ACCEPT ALL OF THESE TERMS. BY USING THE APP, THE SMART CONTRACTS, THE SITE, OR ANY PART OF THEM, OR BY CLICKING “I ACCEPT” BELOW OR INDICATING YOUR ACCEPTANCE IN AN ADJOINING BOX, YOU ARE CONFIRMING THAT YOU UNDERSTAND AND AGREE TO BE BOUND BY ALL OF THESE TERMS. IF YOU ARE ACCEPTING THESE TERMS ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY TO ACCEPT THESE TERMS ON THAT ENTITY’S BEHALF, IN WHICH CASE “YOU” WILL MEAN THAT ENTITY. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT ACCEPT ALL OF THESE TERMS, THEN WE ARE UNWILLING TO MAKE THE APP, THE SMART CONTRACTS, OR THE SITE AVAILABLE TO YOU. IF YOU DO NOT AGREE TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE APP, THE SMART CONTRACTS, OR THE SITE.</p>
            <p>1. Our CryptoKitties</p>
            <p>A. We have utilized Smart Contracts to develop our initial generation of CryptoKitties (“Gen-Zero cats”). We will release a certain number of Gen-Zero cats “into the wild” (and make them available for purchase) on the day we first launch the App. We will then release an additional Gen-Zero cat into the wild every fifteen minutes, and we will make each newly-released Gen-Zero cat available for purchase via a zero-reserve clock auction. Our Smart Contracts enforce a hard limit of 50,000 Gen-Zero cats.</p>
            <p>B. As users breed their CryptoKitties, new and unforeseen generations of CryptoKitties will come into existence! Using our proprietary genetic combination algorithm that we have designed as part of the App, each newly-bred CryptoKitty will have some of the genetic traits of its parents. At the same time, other, new genetic traits may be expressed. Unique and surprising traits may be expressed when CryptoKitties are bred in the right combinations. The Smart Contracts have total control over the pseudo-random elements of our breeding process, which means that we cannot manipulate or influence them.</p>
            <p>C. How you breed your CryptoKitties is entirely up to you. You may breed your own CryptoKitties with one another, or offer to breed your CryptoKitties with other users’ CryptoKitties. Our CryptoKitties have no fixed gender, which means that in any particular breeding transaction, the CryptoKitties’ owners can choose which cat will be the sire, and which will be the matron. When the new kitten is born, it will always be assigned to the owner of the matron cat. The breeding of two CryptoKitties will always produce a kitten.</p>
            -->
            <p>1. The App</p>
            <p>A. To most easily use the App, you must first install the Google Chrome web browser. Once you have installed Chrome, you will need to install a browser extension called MetaMask. MetaMask is an electronic wallet, which allows you to purchase (either directly via Coinbase if you are in the United States, or via other third party sites), store, and engage in transactions using Ethereum cryptocurrency. You will not be able to engage in any transactions on the App other than through MetaMask (or other Ethereum-compatible browsers). The App will only recognize you as a user, and you will only be able to interact with the App, if your Ethereum electronic wallet is connected and unlocked through your MetaMask account. There is no other way to sign up as a user, or to interact directly with the App.</p>
            <p>B. Transactions that take place on the App are managed and confirmed via the Ethereum blockchain. You understand that your Ethereum public address will be made publicly visible whenever you engage in a transaction on the App.</p>
            <p>C. We neither own nor control MetaMask, Coinbase, Google Chrome, the Ethereum network, or any other third party site, product, or service that you might access, visit, or use for the purpose of enabling you to use the various features of the App. We will not be liable for the acts or omissions of any such third parties, nor will we be liable for any damage that you may suffer as a result of your transactions or any other interaction with any such third parties.</p>
            <p>D. You must provide accurate and complete registration information when you create an account for the App. By creating an account, you agree to provide accurate, current and complete account information about yourself, and to maintain and promptly update as necessary your account information. You are responsible for the security of your account and your MetaMask wallet (and other Ethereum wallets and accounts). If you become aware of any unauthorized use of your password or of your account with us, you agree to notify us immediately at xuefeng1019@gmail.com.</p>
            <p>2. Fees and Payment</p>
            <p>A. If you elect to purchase on the App, any financial transactions that you engage in will be conducted solely through the Ethereum network via via MetaMask. We will have no insight into or control over these payments or transactions, nor do we have the ability to reverse any transactions. With that in mind, we will have no liability to you or to any third party for any claims or damages that may arise as a result of any transactions that you engage in via the App, or using the Smart Contracts, or any other transactions that you conduct via the Ethereum network or MetaMask.</p>
            <p>B. Ethereum requires the payment of a transaction fee (a “Gas Fee”) for every transaction that occurs on the Ethereum network. The Gas Fee funds the network of computers that run the decentralized Ethereum network. This means that you will need to pay a Gas Fee for each transaction that occurs via the App.</p>
            <p>C. As between us, you will be solely responsible to pay any and all sales, use, value-added and other taxes, duties, and assessments (except taxes on our net income) now or hereafter claimed or imposed by any governmental authority (collectively, “Taxes”) associated with your use of the App. Except for income taxes levied on Axiom Zen, you: (i) will pay or reimburse us for all national, federal, state, local or other taxes and assessments of any jurisdiction, including value added taxes and taxes as required by international tax treaties, customs or other import or export taxes, and amounts levied in lieu thereof based on charges set, services performed or payments made hereunder, as are now or hereafter may be imposed under the authority of any national, state, local or any other taxing jurisdiction; and (ii) shall not be entitled to deduct the amount of any such taxes, duties or assessments from payments made to us pursuant to these Terms.</p>
            <p>3. Ownership; Restrictions</p>
            <p>A. You acknowledge and agree that we (or, as applicable, our licensors) own all legal right, title and interest in and to all elements of the App, and all intellectual property rights therein. The visual interfaces, graphics (including, without limitation, all art and drawings associated with the EncryptBuy), design, systems, methods, information, computer code, software, services, “look and feel”, organization, compilation of the content, code, data, and all other elements of the App are owned by Beijing Ninety Technology Co., Ltd., and are protected by copyright, trade dress, patent, and trademark laws, international conventions, other relevant intellectual property and proprietary rights, and applicable laws.Except as expressly set forth herein, your use of the App does not grant you ownership of or any other rights with respect to any content, code, data, or other materials that you may access on or through the App.</p>
            <p>B. You may choose to submit comments, bug reports, ideas or other feedback about the App, including without limitation about how to improve the App (collectively, “Feedback”).&nbsp;By submitting any Feedback, you agree that we are free to use such Feedback at our discretion and without additional compensation to you, and to disclose such Feedback to third parties (whether on a non-confidential basis, or otherwise).&nbsp;You hereby grant us a perpetual, irrevocable, nonexclusive, worldwide license under all rights necessary for us to incorporate and use your Feedback for any purpose.</p>
            <p>C. You agree that you are responsible for your own conduct while accessing or using the App, and for any consequences thereof. You agree to use the App only for purposes that are legal, proper and in accordance with these Terms and any applicable laws or regulations. By way of example, and not as a limitation, you may not, and may not allow any third party to: (i) send, upload, distribute or disseminate any unlawful, defamatory, harassing, abusive, fraudulent, obscene, or otherwise objectionable content; (ii) distribute viruses, worms, defects, Trojan horses, corrupted files, hoaxes, or any other items of a destructive or deceptive nature; (iii) impersonate another person (via the use of an email address or otherwise); (iv) upload, post, transmit or otherwise make available through the App any content that infringes the intellectual proprietary rights of any party; (v) use the App to violate the legal rights (such as rights of privacy and publicity) of others; (vi) engage in, promote, or encourage illegal activity (including, without limitation, money laundering); (vii) interfere with other users’ enjoyment of the App; (viii) exploit the App for any unauthorized commercial purpose; (ix) modify, adapt, translate, or reverse engineer any portion of the App; (x) remove any copyright, trademark or other proprietary rights notices contained in or on the App or any part of it; (xi) reformat or frame any portion of the App; (xii) display any content on the App that contains any hate-related or violent content or contains any other material, products or services that violate or encourage conduct that would violate any criminal laws, any other applicable laws, or any third party rights; (xiii) use any robot, spider, site search/retrieval application, or other device to retrieve or index any portion of the App or the content posted on the App, or to collect information about its users for any unauthorized purpose; (xiv) create user accounts by automated means or under false or fraudulent pretenses; or (xv) access or use the App for the purpose of creating a product or service that is competitive with any of our products or services.</p>
            <p>4. Termination</p>
            <p>You may terminate these Terms at any time by canceling your account on the App and discontinuing your access to and use of the App.&nbsp;You will not receive any refunds if you cancel your account, or otherwise terminate these Terms. You agree that we, in our sole discretion and for any or no reason, may terminate these Terms and suspend and/or terminate your account(s) for the App.&nbsp;You agree that any suspension or termination of your access to the App may be without prior notice, and that we will not be liable to you or to any third party for any such suspension or termination.&nbsp;If we terminate these Terms or suspend or terminate your access to or use of the App due to your breach of these Terms or any suspected fraudulent, abusive, or illegal activity, then termination of these Terms will be in addition to any other remedies we may have at law or in equity. Upon any termination or expiration of these Terms, whether by you or us, you may no longer have access to information that you have posted on the App or that is related to your account, and you acknowledge that we will have no obligation to maintain any such information in our databases or to forward any such information to you or to any third party. Sections 2.C and 3 through 16 will survive the termination or expiration of these Terms for any reason.</p>
            <p>5. Disclaimers</p>
            <p>A. You expressly understand and agree that your access to and use of the app is at your sole risk, and that the app is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, whether express or implied. To the fullest extent permissible pursuant to applicable law, we, our subsidiaries, affiliates, and licensors make no express warranties and hereby disclaim all implied warranties regarding the app and any part of it (including, without limitation, the site, any smart contract, or any external websites), including the implied warranties of merchantability, fitness for a particular purpose, non-infringement, correctness, accuracy, or reliability.&nbsp;Without limiting the generality of the foregoing, we, our subsidiaries, affiliates, and licensors do not represent or warrant to you that: (i)&nbsp;Your access to or use of the app will meet your requirements, (ii)&nbsp;Your access to or use of the app will be uninterrupted, timely, secure or free from error, (iii)&nbsp;Usage data provided through the app will be accurate, (iii) The app or any content, services, or features made available on or through the app are free of viruses or other harmful components, or (iv) That any data that you disclose when you use the app will be secure. Some jurisdictions do not allow the exclusion of implied warranties in contracts with consumers, so some or all of the above exclusions may not apply to you.</p>
            <p>B. You accept the inherent security risks of providing information and dealing online over the internet, and agree that we have no liability or responsibility for any breach of security unless it is due to our gross negligence.</p>
            <p>C. We will not be responsible or liable to you for any losses you incur as the result of your use of the ethereum network or the metamask electronic wallet, including but not limited to any losses, damages or claims arising from: (a) User error, such as forgotten passwords or incorrectly construed smart contracts or other transactions; (b) Server failure or data loss; (c) Corrupted wallet files; (d) Unauthorized access or activities by third parties, including but not limited to the use of viruses, phishing, bruteforcing or other means of attack against the app, ethereum network, or the metamask electronic wallet.</p>
            <p>D. All smart contracts are conducted and occur on the decentralized ledger within the ethereum platform. We have no control over and make no guarantees or promises with respect to smart contracts.</p>
            <p>E. The Encryptbuy is not responsible for losses due to blockchains or any other features of the ethereum network or the metamask electronic wallet, including but not limited to late report by developers or representatives (or no report at all) of any issues with the blockchain supporting the ethereum network, including forks, technical node issues, or any other issues having fund losses as a result.</p>
            <p>6. Limitation of Liability</p>
            <p>A. You understand and agree that we, our subsidiaries, affiliates, and licensors will not be liable to you or to any third party for any indirect, incidental, special, consequential, or exemplary damages which you may incur, howsoever caused and under any theory of liability, including, without limitation, any loss of profits (whether incurred directly or indirectly), loss of goodwill or business reputation, loss of data, cost of procurement of substitute goods or services, or any other intangible loss, even if we have been advised of the possibility of such damages.</p>
            <p>B. You agree that our total, aggregate liability to you for any and all claims arising out of or relating to these terms or your access to or use of (or your inability to access or use) any portion of the app, whether in contract, tort, strict liability, or any other legal theory, is limited to the greater of (a) the amounts you actually paid us under these terms in the 12 month period preceding the date the claim arose, or (b) $50.</p>
            <p>C. You acknowledge and agree that we have made the app available to you and entered into these terms in reliance upon the warranty disclaimers and limitations of liability set forth herein, which reflect a reasonable and fair allocation of risk between the parties and form an essential basis of the bargain between us. We would not be able to provide the app to you without these limitations.</p>
            <p>D. Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, and some jurisdictions also limit disclaimers or limitations of liability for personal injury from consumer products, so the above limitations may not apply to personal injury claims.</p>
            <p>7. Assumption of Risk</p>
            <p>You accept and acknowledge each of the following:</p>
            <p>A. You are solely responsible for determining what, if any, taxes apply to your EncryptBuy-related transactions. We are not responsible for determining the taxes that apply to your transactions on the App, the Site, or the Smart Contracts.</p>
            <p>B. There are risks associated with using an Internet-based currency, including, but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your wallet. You accept and acknowledge that we will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Ethereum network, however caused.</p>
            <p>C. A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of the EncryptBuy ecosystem, and therefore the potential utility or value of EncryptBuy.</p>
            <p>D. The regulatory regime governing blockchain technologies, cryptocurrencies, and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the EncryptBuy ecosystem, and therefore the potential utility or value of EncryptBuy.</p>
            <p>E. Upgrades by Ethereum to the Ethereum platform, a hard fork in the Ethereum platform, or a change in how transactions are confirmed on the Ethereum platform may have unintended, adverse effects on all blockchains using the ERC-20 standard, including the EncryptBuy ecosystem.</p>
            <p>8. Indemnification</p>
            <p>You agree to hold harmless and indemnify Beijing Ninety Technology Co., Ltd. and its subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers or partners from and against any claim, liability, loss, damage (actual and consequential) of any kind or nature, suit, judgment, litigation cost, and attorneys’ fees arising out of or in any way related to (i)&nbsp;your breach of these Terms, (ii) your misuse of the App, or (iii) your violation of applicable laws, rules or regulations in connection with your access to or use of the App.&nbsp; You agree that Beijing Ninety Technology Co., Ltd. will have control of the defense or settlement of any such claims.</p>
            <p>9. External Sites</p>
            <p>The App may include hyperlinks to other web sites or resources (collectively, “External Sites”), which are provided solely as a convenience to our users. We have no control over any External Sites. You acknowledge and agree that we are not responsible for the availability of any External Sites, and that we do not endorse any advertising, products or other materials on or made available from any External Sites. Furthermore, you acknowledge and agree that we are not liable for any loss or damage which may be incurred as a result of the availability or unavailability of the External Sites, or as a result of any reliance placed by you upon the completeness, accuracy or existence of any advertising, products or other materials on, or made available from, any External Sites.</p>
            <p>10. Changes to the Terms</p>
            <p>The App may include hyperlinks to other web sites or resources (collectively, “External Sites”), which are provided solely as a convenience to our users.&nbsp;We have no control over any External Sites. You acknowledge and agree that we are not responsible for the availability of any External Sites, and that we do not endorse any advertising, products or other materials on or made available from any External Sites. Furthermore, you acknowledge and agree that we are not liable for any loss or damage which may be incurred as a result of the availability or unavailability of the External Sites, or as a result of any reliance placed by you upon the completeness, accuracy or existence of any advertising, products or other materials on, or made available from, any External Sites.</p>
            <p>11. Changes to the App</p>
            <p>We may make changes to the Terms from time to time.&nbsp;When we make changes, we will make the updated Terms available on the App and update the “Last Updated” date at the beginning of these Terms accordingly.&nbsp;Please check these Terms periodically for changes.&nbsp;Any changes to the Terms will apply on the date that they are made, and your continued access to or use of the App after the Terms have been updated will constitute your binding acceptance of the updates.&nbsp; If you do not agree to any revised Terms, you may not access or use the App.</p>
            <p>12. Children</p>
            <p>You affirm that you are over the age of 16, as the app is not intended for children under 16.&nbsp;If you are 16 or older but under the age of 18, or the legal age of majority where you reside if that jurisdiction has an older age of majority, then you agree to review these terms with your parent or guardian to make sure that both you and your parent or guardian understand and agree to these terms.&nbsp;You agree to have your parent or guardian review and accept these terms on your behalf.&nbsp;If you are a parent or guardian agreeing to the terms for the benefit of a child over 16, then you agree to and accept full responsibility for that child’s use of the app, including all financial charges and legal liability that he or she may incur.</p>
            <p>13. Privacy Policy</p>
            <p><span>Our <a aria-current="false" href="/privacy-policy">Privacy Policy</a> describes the ways we collect, use, store and disclose your personal information, and is hereby incorporated by this reference into these Terms. You agree to the collection, use, storage, and disclosure of your data in accordance with our <a aria-current="false" href="/privacy-policy">Privacy Policy</a></span></p>
            <p>14. General</p>
            <p>These Terms constitute the entire legal agreement between you and Beijing Ninety Technology Co., Ltd., govern your access to and use of the App, and completely replace any prior or contemporaneous agreements between the parties related to your access to or use of the App, whether oral or written. There are no third party beneficiaries to these Terms. The parties are independent contractors, and nothing in these Terms create any agency, partnership, or joint venture. The language in these Terms will be interpreted as to its fair meaning, and not strictly for or against any party. You may not assign any or your rights or obligations under these Terms, whether by operation of law or otherwise, without our prior written consent. We may assign our rights and obligations under these Terms in our sole discretion to an affiliate, or in connection with an acquisition, sale or merger. Should any part of these Terms be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions will remain in full force and effect. Our failure to enforce any provision of these Terms will not be deemed a waiver of such provision, nor of the right to enforce such provision. These Terms will be governed by and construed in accordance with the laws of the province of British Columbia, Canada and the federal laws of Canada applicable therein, excluding its conflicts of law rules and principles. Subject to Section 15, any legal action or proceeding arising under these Terms will be brought exclusively in the federal or provincial courts located in Vancouver, British Columbia, and the parties irrevocably consent to the personal jurisdiction and venue there. We will not be liable for any failure or delayed performance of our obligations that result from any condition beyond our reasonable control, including, but not limited to, governmental action, acts of terrorism, earthquake, fire, flood, acts of God, labor conditions, power failures, Internet disturbances, or acts or omissions of third parties. You agree that we may provide you with notices (including, without limitation those regarding changes to these Terms) by email, regular mail, or postings on the App.&nbsp;By providing us with your email address, you consent to our using the email address to send you any notices required by law in lieu of communication by postal mail.</p>
        </div>
    </div>
</main>
<?php include_once 'api/views/__footer.tpl'?>
</body>
</html>